export type Continent =
  | 'Europe'
  | 'Asia'
  | 'North America'
  | 'South America'
  | 'Africa'
  | 'Oceania'
  | 'Unknown';

export const ALL_CONTINENTS: Continent[] = [
  'Europe',
  'Asia',
  'North America',
  'South America',
  'Africa',
  'Oceania',
];

const CONTINENT_MAP: Record<string, Continent> = {
  // Europe
  GB: 'Europe',
  DE: 'Europe',
  FR: 'Europe',
  IT: 'Europe',
  ES: 'Europe',
  PT: 'Europe',
  NL: 'Europe',
  BE: 'Europe',
  AT: 'Europe',
  CH: 'Europe',
  PL: 'Europe',
  CZ: 'Europe',
  GR: 'Europe',
  SE: 'Europe',
  NO: 'Europe',
  DK: 'Europe',
  FI: 'Europe',
  IE: 'Europe',
  HU: 'Europe',
  RO: 'Europe',
  BG: 'Europe',
  HR: 'Europe',
  SK: 'Europe',
  SI: 'Europe',
  LT: 'Europe',
  LV: 'Europe',
  EE: 'Europe',
  CY: 'Europe',
  MT: 'Europe',
  LU: 'Europe',
  IS: 'Europe',
  TR: 'Europe',
  UA: 'Europe',
  BY: 'Europe',
  RS: 'Europe',
  BA: 'Europe',
  AL: 'Europe',
  MK: 'Europe',
  ME: 'Europe',
  XK: 'Europe',
  MD: 'Europe',
  RU: 'Europe',
  MC: 'Europe',
  AD: 'Europe',
  SM: 'Europe',
  VA: 'Europe',
  LI: 'Europe',

  // North America
  US: 'North America',
  CA: 'North America',
  MX: 'North America',
  GT: 'North America',
  CU: 'North America',
  DO: 'North America',
  HT: 'North America',
  JM: 'North America',
  PR: 'North America',
  PA: 'North America',
  CR: 'North America',
  NI: 'North America',
  HN: 'North America',
  SV: 'North America',
  BZ: 'North America',
  BB: 'North America',
  BS: 'North America',
  TT: 'North America',
  AW: 'North America',
  CW: 'North America',
  KY: 'North America',
  VI: 'North America',
  AG: 'North America',
  LC: 'North America',
  GD: 'North America',
  VC: 'North America',
  DM: 'North America',
  KN: 'North America',
  TC: 'North America',
  BM: 'North America',
  MQ: 'North America',
  GP: 'North America',
  SX: 'North America',
  MF: 'North America',
  BQ: 'North America',

  // South America
  BR: 'South America',
  AR: 'South America',
  CO: 'South America',
  PE: 'South America',
  VE: 'South America',
  CL: 'South America',
  EC: 'South America',
  BO: 'South America',
  PY: 'South America',
  UY: 'South America',
  GY: 'South America',
  SR: 'South America',
  GF: 'South America',
  FK: 'South America',

  // Asia
  CN: 'Asia',
  JP: 'Asia',
  KR: 'Asia',
  IN: 'Asia',
  ID: 'Asia',
  TH: 'Asia',
  VN: 'Asia',
  MY: 'Asia',
  SG: 'Asia',
  PH: 'Asia',
  PK: 'Asia',
  BD: 'Asia',
  LK: 'Asia',
  NP: 'Asia',
  MM: 'Asia',
  KH: 'Asia',
  LA: 'Asia',
  TW: 'Asia',
  HK: 'Asia',
  MO: 'Asia',
  AE: 'Asia',
  SA: 'Asia',
  QA: 'Asia',
  KW: 'Asia',
  BH: 'Asia',
  OM: 'Asia',
  JO: 'Asia',
  LB: 'Asia',
  IL: 'Asia',
  IQ: 'Asia',
  IR: 'Asia',
  AF: 'Asia',
  KZ: 'Asia',
  UZ: 'Asia',
  TM: 'Asia',
  KG: 'Asia',
  TJ: 'Asia',
  AZ: 'Asia',
  GE: 'Asia',
  AM: 'Asia',
  MN: 'Asia',
  KP: 'Asia',
  BN: 'Asia',
  TL: 'Asia',
  MV: 'Asia',
  BT: 'Asia',
  YE: 'Asia',
  SY: 'Asia',
  PS: 'Asia',

  // Africa
  EG: 'Africa',
  ZA: 'Africa',
  NG: 'Africa',
  KE: 'Africa',
  ET: 'Africa',
  MA: 'Africa',
  DZ: 'Africa',
  TN: 'Africa',
  LY: 'Africa',
  GH: 'Africa',
  TZ: 'Africa',
  UG: 'Africa',
  ZW: 'Africa',
  ZM: 'Africa',
  BW: 'Africa',
  NA: 'Africa',
  MZ: 'Africa',
  AO: 'Africa',
  SN: 'Africa',
  CI: 'Africa',
  CM: 'Africa',
  MU: 'Africa',
  RW: 'Africa',
  MW: 'Africa',
  MG: 'Africa',
  SD: 'Africa',
  SS: 'Africa',
  CD: 'Africa',
  CG: 'Africa',
  GA: 'Africa',
  GQ: 'Africa',
  CF: 'Africa',
  TD: 'Africa',
  NE: 'Africa',
  ML: 'Africa',
  BF: 'Africa',
  BJ: 'Africa',
  TG: 'Africa',
  GN: 'Africa',
  SL: 'Africa',
  LR: 'Africa',
  MR: 'Africa',
  GM: 'Africa',
  GW: 'Africa',
  CV: 'Africa',
  ST: 'Africa',
  DJ: 'Africa',
  ER: 'Africa',
  SO: 'Africa',
  SC: 'Africa',
  KM: 'Africa',
  RE: 'Africa',
  YT: 'Africa',
  SZ: 'Africa',
  LS: 'Africa',

  // Oceania
  AU: 'Oceania',
  NZ: 'Oceania',
  FJ: 'Oceania',
  PG: 'Oceania',
  NC: 'Oceania',
  PF: 'Oceania',
  GU: 'Oceania',
  WS: 'Oceania',
  VU: 'Oceania',
  SB: 'Oceania',
  TO: 'Oceania',
  FM: 'Oceania',
  PW: 'Oceania',
  MH: 'Oceania',
  KI: 'Oceania',
  NR: 'Oceania',
  TV: 'Oceania',
  AS: 'Oceania',
  CK: 'Oceania',
  NU: 'Oceania',
  TK: 'Oceania',
  WF: 'Oceania',
  MP: 'Oceania',
};

export function getContinent(countryIso: string | null): Continent {
  if (!countryIso) return 'Unknown';
  return CONTINENT_MAP[countryIso.toUpperCase()] || 'Unknown';
}

export function getContinentColor(continent: Continent): string {
  const colors: Record<Continent, string> = {
    Europe: '#3b82f6',
    Asia: '#ef4444',
    'North America': '#22c55e',
    'South America': '#f59e0b',
    Africa: '#8b5cf6',
    Oceania: '#06b6d4',
    Unknown: '#6b7280',
  };
  return colors[continent];
}
