import { UK_MAP_UNITS } from './uk-map-units.data';

/**
 * Which of the UK's four countries a point is in (2026-10-03).
 *
 * The UK is no longer one country in the app: England, Scotland, Wales and
 * Northern Ireland are countries in their own right, keyed by their ISO
 * 3166-2 codes. Airports and cities from the source datasets only say
 * "GB", so every GB row is placed by its coordinates against the same
 * Natural Earth polygons the map draws - the data file is generated by
 * frontend/scripts/build-world-atlas.mjs, so the backend's answer and the
 * painted border can never disagree.
 *
 * Offshore points (a coastal airport whose runway pokes past the 50m
 * coastline, a harbour town on a skerry too small to draw) snap to the
 * country with the nearest polygon vertex. Coasts between the four are
 * far apart, so "nearest vertex" is the same as "nearest coast" here.
 */
export type UkConstituentIso = 'GB-ENG' | 'GB-SCT' | 'GB-WLS' | 'GB-NIR';

export const UK_CONSTITUENTS: Record<UkConstituentIso, { name: string; alpha3: string }> = {
  'GB-ENG': { name: 'England', alpha3: 'ENG' },
  'GB-SCT': { name: 'Scotland', alpha3: 'SCT' },
  'GB-WLS': { name: 'Wales', alpha3: 'WLS' },
  'GB-NIR': { name: 'Northern Ireland', alpha3: 'NIR' },
};

export const UK_CONSTITUENT_ISOS = Object.keys(UK_CONSTITUENTS) as UkConstituentIso[];

/** The display name for a UK country code, or undefined for any other code. */
export function ukConstituentName(iso: string): string | undefined {
  return (UK_CONSTITUENTS as Record<string, { name: string }>)[iso]?.name;
}

/** Even-odd ray cast: is [lon, lat] inside this ring? */
function ringContains(ring: number[][], lon: number, lat: number): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    const crosses =
      yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
    if (crosses) inside = !inside;
  }
  return inside;
}

/** Outer ring contains the point and no hole does. */
function polygonContains(polygon: number[][][], lon: number, lat: number): boolean {
  if (!ringContains(polygon[0], lon, lat)) return false;
  for (let h = 1; h < polygon.length; h++) {
    if (ringContains(polygon[h], lon, lat)) return false;
  }
  return true;
}

/** Squared distance in degrees, latitude-corrected - fine at UK scale. */
function nearestVertexDistance(polygons: number[][][][], lon: number, lat: number): number {
  const cos = Math.cos((lat * Math.PI) / 180);
  let best = Infinity;
  for (const polygon of polygons) {
    for (const ring of polygon) {
      for (const [x, y] of ring) {
        const dx = (x - lon) * cos;
        const dy = y - lat;
        const d = dx * dx + dy * dy;
        if (d < best) best = d;
      }
    }
  }
  return best;
}

export function ukConstituentFor(latitude: number, longitude: number): UkConstituentIso {
  for (const iso of UK_CONSTITUENT_ISOS) {
    for (const polygon of UK_MAP_UNITS[iso]) {
      if (polygonContains(polygon, longitude, latitude)) return iso;
    }
  }
  let nearest: UkConstituentIso = 'GB-ENG';
  let nearestDistance = Infinity;
  for (const iso of UK_CONSTITUENT_ISOS) {
    const d = nearestVertexDistance(UK_MAP_UNITS[iso], longitude, latitude);
    if (d < nearestDistance) {
      nearestDistance = d;
      nearest = iso;
    }
  }
  return nearest;
}
