import { DataSource } from 'typeorm';
import { Country } from '../modules/countries/entities/country.entity';

export const countriesData = [
  { name: 'Afghanistan', isoCode: 'AFG', isoCode2: 'AF' },
  { name: 'Albania', isoCode: 'ALB', isoCode2: 'AL' },
  { name: 'Algeria', isoCode: 'DZA', isoCode2: 'DZ' },
  { name: 'Andorra', isoCode: 'AND', isoCode2: 'AD' },
  { name: 'Angola', isoCode: 'AGO', isoCode2: 'AO' },
  { name: 'Antigua and Barbuda', isoCode: 'ATG', isoCode2: 'AG' },
  { name: 'Argentina', isoCode: 'ARG', isoCode2: 'AR' },
  { name: 'Armenia', isoCode: 'ARM', isoCode2: 'AM' },
  { name: 'Australia', isoCode: 'AUS', isoCode2: 'AU' },
  { name: 'Austria', isoCode: 'AUT', isoCode2: 'AT' },
  { name: 'Azerbaijan', isoCode: 'AZE', isoCode2: 'AZ' },
  { name: 'Bahamas', isoCode: 'BHS', isoCode2: 'BS' },
  { name: 'Bahrain', isoCode: 'BHR', isoCode2: 'BH' },
  { name: 'Bangladesh', isoCode: 'BGD', isoCode2: 'BD' },
  { name: 'Barbados', isoCode: 'BRB', isoCode2: 'BB' },
  { name: 'Belarus', isoCode: 'BLR', isoCode2: 'BY' },
  { name: 'Belgium', isoCode: 'BEL', isoCode2: 'BE' },
  { name: 'Belize', isoCode: 'BLZ', isoCode2: 'BZ' },
  { name: 'Benin', isoCode: 'BEN', isoCode2: 'BJ' },
  { name: 'Bhutan', isoCode: 'BTN', isoCode2: 'BT' },
  { name: 'Bolivia', isoCode: 'BOL', isoCode2: 'BO' },
  { name: 'Bosnia and Herzegovina', isoCode: 'BIH', isoCode2: 'BA' },
  { name: 'Botswana', isoCode: 'BWA', isoCode2: 'BW' },
  { name: 'Brazil', isoCode: 'BRA', isoCode2: 'BR' },
  { name: 'Brunei', isoCode: 'BRN', isoCode2: 'BN' },
  { name: 'Bulgaria', isoCode: 'BGR', isoCode2: 'BG' },
  { name: 'Burkina Faso', isoCode: 'BFA', isoCode2: 'BF' },
  { name: 'Burundi', isoCode: 'BDI', isoCode2: 'BI' },
  { name: 'Cabo Verde', isoCode: 'CPV', isoCode2: 'CV' },
  { name: 'Cambodia', isoCode: 'KHM', isoCode2: 'KH' },
  { name: 'Cameroon', isoCode: 'CMR', isoCode2: 'CM' },
  { name: 'Canada', isoCode: 'CAN', isoCode2: 'CA' },
  { name: 'Central African Republic', isoCode: 'CAF', isoCode2: 'CF' },
  { name: 'Chad', isoCode: 'TCD', isoCode2: 'TD' },
  { name: 'Chile', isoCode: 'CHL', isoCode2: 'CL' },
  { name: 'China', isoCode: 'CHN', isoCode2: 'CN' },
  { name: 'Colombia', isoCode: 'COL', isoCode2: 'CO' },
  { name: 'Comoros', isoCode: 'COM', isoCode2: 'KM' },
  { name: 'Congo', isoCode: 'COG', isoCode2: 'CG' },
  { name: 'Costa Rica', isoCode: 'CRI', isoCode2: 'CR' },
  { name: 'Croatia', isoCode: 'HRV', isoCode2: 'HR' },
  { name: 'Cuba', isoCode: 'CUB', isoCode2: 'CU' },
  { name: 'Cyprus', isoCode: 'CYP', isoCode2: 'CY' },
  { name: 'Czech Republic', isoCode: 'CZE', isoCode2: 'CZ' },
  { name: 'Democratic Republic of the Congo', isoCode: 'COD', isoCode2: 'CD' },
  { name: 'Denmark', isoCode: 'DNK', isoCode2: 'DK' },
  { name: 'Djibouti', isoCode: 'DJI', isoCode2: 'DJ' },
  { name: 'Dominica', isoCode: 'DMA', isoCode2: 'DM' },
  { name: 'Dominican Republic', isoCode: 'DOM', isoCode2: 'DO' },
  { name: 'Ecuador', isoCode: 'ECU', isoCode2: 'EC' },
  { name: 'Egypt', isoCode: 'EGY', isoCode2: 'EG' },
  { name: 'El Salvador', isoCode: 'SLV', isoCode2: 'SV' },
  { name: 'Equatorial Guinea', isoCode: 'GNQ', isoCode2: 'GQ' },
  { name: 'Eritrea', isoCode: 'ERI', isoCode2: 'ER' },
  { name: 'Estonia', isoCode: 'EST', isoCode2: 'EE' },
  { name: 'Eswatini', isoCode: 'SWZ', isoCode2: 'SZ' },
  { name: 'Ethiopia', isoCode: 'ETH', isoCode2: 'ET' },
  { name: 'Fiji', isoCode: 'FJI', isoCode2: 'FJ' },
  { name: 'Finland', isoCode: 'FIN', isoCode2: 'FI' },
  { name: 'France', isoCode: 'FRA', isoCode2: 'FR' },
  { name: 'Gabon', isoCode: 'GAB', isoCode2: 'GA' },
  { name: 'Gambia', isoCode: 'GMB', isoCode2: 'GM' },
  { name: 'Georgia', isoCode: 'GEO', isoCode2: 'GE' },
  { name: 'Germany', isoCode: 'DEU', isoCode2: 'DE' },
  { name: 'Ghana', isoCode: 'GHA', isoCode2: 'GH' },
  { name: 'Greece', isoCode: 'GRC', isoCode2: 'GR' },
  { name: 'Grenada', isoCode: 'GRD', isoCode2: 'GD' },
  { name: 'Guatemala', isoCode: 'GTM', isoCode2: 'GT' },
  { name: 'Guinea', isoCode: 'GIN', isoCode2: 'GN' },
  { name: 'Guinea-Bissau', isoCode: 'GNB', isoCode2: 'GW' },
  { name: 'Guyana', isoCode: 'GUY', isoCode2: 'GY' },
  { name: 'Haiti', isoCode: 'HTI', isoCode2: 'HT' },
  { name: 'Honduras', isoCode: 'HND', isoCode2: 'HN' },
  { name: 'Hungary', isoCode: 'HUN', isoCode2: 'HU' },
  { name: 'Iceland', isoCode: 'ISL', isoCode2: 'IS' },
  { name: 'India', isoCode: 'IND', isoCode2: 'IN' },
  { name: 'Indonesia', isoCode: 'IDN', isoCode2: 'ID' },
  { name: 'Iran', isoCode: 'IRN', isoCode2: 'IR' },
  { name: 'Iraq', isoCode: 'IRQ', isoCode2: 'IQ' },
  { name: 'Ireland', isoCode: 'IRL', isoCode2: 'IE' },
  { name: 'Israel', isoCode: 'ISR', isoCode2: 'IL' },
  { name: 'Italy', isoCode: 'ITA', isoCode2: 'IT' },
  { name: 'Ivory Coast', isoCode: 'CIV', isoCode2: 'CI' },
  { name: 'Jamaica', isoCode: 'JAM', isoCode2: 'JM' },
  { name: 'Japan', isoCode: 'JPN', isoCode2: 'JP' },
  { name: 'Jordan', isoCode: 'JOR', isoCode2: 'JO' },
  { name: 'Kazakhstan', isoCode: 'KAZ', isoCode2: 'KZ' },
  { name: 'Kenya', isoCode: 'KEN', isoCode2: 'KE' },
  { name: 'Kiribati', isoCode: 'KIR', isoCode2: 'KI' },
  { name: 'Kosovo', isoCode: 'XKX', isoCode2: 'XK' },
  { name: 'Kuwait', isoCode: 'KWT', isoCode2: 'KW' },
  { name: 'Kyrgyzstan', isoCode: 'KGZ', isoCode2: 'KG' },
  { name: 'Laos', isoCode: 'LAO', isoCode2: 'LA' },
  { name: 'Latvia', isoCode: 'LVA', isoCode2: 'LV' },
  { name: 'Lebanon', isoCode: 'LBN', isoCode2: 'LB' },
  { name: 'Lesotho', isoCode: 'LSO', isoCode2: 'LS' },
  { name: 'Liberia', isoCode: 'LBR', isoCode2: 'LR' },
  { name: 'Libya', isoCode: 'LBY', isoCode2: 'LY' },
  { name: 'Liechtenstein', isoCode: 'LIE', isoCode2: 'LI' },
  { name: 'Lithuania', isoCode: 'LTU', isoCode2: 'LT' },
  { name: 'Luxembourg', isoCode: 'LUX', isoCode2: 'LU' },
  { name: 'Madagascar', isoCode: 'MDG', isoCode2: 'MG' },
  { name: 'Malawi', isoCode: 'MWI', isoCode2: 'MW' },
  { name: 'Malaysia', isoCode: 'MYS', isoCode2: 'MY' },
  { name: 'Maldives', isoCode: 'MDV', isoCode2: 'MV' },
  { name: 'Mali', isoCode: 'MLI', isoCode2: 'ML' },
  { name: 'Malta', isoCode: 'MLT', isoCode2: 'MT' },
  { name: 'Marshall Islands', isoCode: 'MHL', isoCode2: 'MH' },
  { name: 'Mauritania', isoCode: 'MRT', isoCode2: 'MR' },
  { name: 'Mauritius', isoCode: 'MUS', isoCode2: 'MU' },
  { name: 'Mexico', isoCode: 'MEX', isoCode2: 'MX' },
  { name: 'Micronesia', isoCode: 'FSM', isoCode2: 'FM' },
  { name: 'Moldova', isoCode: 'MDA', isoCode2: 'MD' },
  { name: 'Monaco', isoCode: 'MCO', isoCode2: 'MC' },
  { name: 'Mongolia', isoCode: 'MNG', isoCode2: 'MN' },
  { name: 'Montenegro', isoCode: 'MNE', isoCode2: 'ME' },
  { name: 'Morocco', isoCode: 'MAR', isoCode2: 'MA' },
  { name: 'Mozambique', isoCode: 'MOZ', isoCode2: 'MZ' },
  { name: 'Myanmar', isoCode: 'MMR', isoCode2: 'MM' },
  { name: 'Namibia', isoCode: 'NAM', isoCode2: 'NA' },
  { name: 'Nauru', isoCode: 'NRU', isoCode2: 'NR' },
  { name: 'Nepal', isoCode: 'NPL', isoCode2: 'NP' },
  { name: 'Netherlands', isoCode: 'NLD', isoCode2: 'NL' },
  { name: 'New Zealand', isoCode: 'NZL', isoCode2: 'NZ' },
  { name: 'Nicaragua', isoCode: 'NIC', isoCode2: 'NI' },
  { name: 'Niger', isoCode: 'NER', isoCode2: 'NE' },
  { name: 'Nigeria', isoCode: 'NGA', isoCode2: 'NG' },
  { name: 'North Korea', isoCode: 'PRK', isoCode2: 'KP' },
  { name: 'North Macedonia', isoCode: 'MKD', isoCode2: 'MK' },
  { name: 'Norway', isoCode: 'NOR', isoCode2: 'NO' },
  { name: 'Oman', isoCode: 'OMN', isoCode2: 'OM' },
  { name: 'Pakistan', isoCode: 'PAK', isoCode2: 'PK' },
  { name: 'Palau', isoCode: 'PLW', isoCode2: 'PW' },
  { name: 'Palestine', isoCode: 'PSE', isoCode2: 'PS' },
  { name: 'Panama', isoCode: 'PAN', isoCode2: 'PA' },
  { name: 'Papua New Guinea', isoCode: 'PNG', isoCode2: 'PG' },
  { name: 'Paraguay', isoCode: 'PRY', isoCode2: 'PY' },
  { name: 'Peru', isoCode: 'PER', isoCode2: 'PE' },
  { name: 'Philippines', isoCode: 'PHL', isoCode2: 'PH' },
  { name: 'Poland', isoCode: 'POL', isoCode2: 'PL' },
  { name: 'Portugal', isoCode: 'PRT', isoCode2: 'PT' },
  { name: 'Qatar', isoCode: 'QAT', isoCode2: 'QA' },
  { name: 'Romania', isoCode: 'ROU', isoCode2: 'RO' },
  { name: 'Russia', isoCode: 'RUS', isoCode2: 'RU' },
  { name: 'Rwanda', isoCode: 'RWA', isoCode2: 'RW' },
  { name: 'Saint Kitts and Nevis', isoCode: 'KNA', isoCode2: 'KN' },
  { name: 'Saint Lucia', isoCode: 'LCA', isoCode2: 'LC' },
  { name: 'Saint Vincent and the Grenadines', isoCode: 'VCT', isoCode2: 'VC' },
  { name: 'Samoa', isoCode: 'WSM', isoCode2: 'WS' },
  { name: 'San Marino', isoCode: 'SMR', isoCode2: 'SM' },
  { name: 'Sao Tome and Principe', isoCode: 'STP', isoCode2: 'ST' },
  { name: 'Saudi Arabia', isoCode: 'SAU', isoCode2: 'SA' },
  { name: 'Senegal', isoCode: 'SEN', isoCode2: 'SN' },
  { name: 'Serbia', isoCode: 'SRB', isoCode2: 'RS' },
  { name: 'Seychelles', isoCode: 'SYC', isoCode2: 'SC' },
  { name: 'Sierra Leone', isoCode: 'SLE', isoCode2: 'SL' },
  { name: 'Singapore', isoCode: 'SGP', isoCode2: 'SG' },
  { name: 'Slovakia', isoCode: 'SVK', isoCode2: 'SK' },
  { name: 'Slovenia', isoCode: 'SVN', isoCode2: 'SI' },
  { name: 'Solomon Islands', isoCode: 'SLB', isoCode2: 'SB' },
  { name: 'Somalia', isoCode: 'SOM', isoCode2: 'SO' },
  { name: 'South Africa', isoCode: 'ZAF', isoCode2: 'ZA' },
  { name: 'South Korea', isoCode: 'KOR', isoCode2: 'KR' },
  { name: 'South Sudan', isoCode: 'SSD', isoCode2: 'SS' },
  { name: 'Spain', isoCode: 'ESP', isoCode2: 'ES' },
  { name: 'Sri Lanka', isoCode: 'LKA', isoCode2: 'LK' },
  { name: 'Sudan', isoCode: 'SDN', isoCode2: 'SD' },
  { name: 'Suriname', isoCode: 'SUR', isoCode2: 'SR' },
  { name: 'Sweden', isoCode: 'SWE', isoCode2: 'SE' },
  { name: 'Switzerland', isoCode: 'CHE', isoCode2: 'CH' },
  { name: 'Syria', isoCode: 'SYR', isoCode2: 'SY' },
  { name: 'Taiwan', isoCode: 'TWN', isoCode2: 'TW' },
  { name: 'Tajikistan', isoCode: 'TJK', isoCode2: 'TJ' },
  { name: 'Tanzania', isoCode: 'TZA', isoCode2: 'TZ' },
  { name: 'Thailand', isoCode: 'THA', isoCode2: 'TH' },
  { name: 'Timor-Leste', isoCode: 'TLS', isoCode2: 'TL' },
  { name: 'Togo', isoCode: 'TGO', isoCode2: 'TG' },
  { name: 'Tonga', isoCode: 'TON', isoCode2: 'TO' },
  { name: 'Trinidad and Tobago', isoCode: 'TTO', isoCode2: 'TT' },
  { name: 'Tunisia', isoCode: 'TUN', isoCode2: 'TN' },
  { name: 'Turkey', isoCode: 'TUR', isoCode2: 'TR' },
  { name: 'Turkmenistan', isoCode: 'TKM', isoCode2: 'TM' },
  { name: 'Tuvalu', isoCode: 'TUV', isoCode2: 'TV' },
  { name: 'Uganda', isoCode: 'UGA', isoCode2: 'UG' },
  { name: 'Ukraine', isoCode: 'UKR', isoCode2: 'UA' },
  { name: 'United Arab Emirates', isoCode: 'ARE', isoCode2: 'AE' },
  { name: 'United Kingdom', isoCode: 'GBR', isoCode2: 'GB' },
  { name: 'United States', isoCode: 'USA', isoCode2: 'US' },
  { name: 'Uruguay', isoCode: 'URY', isoCode2: 'UY' },
  { name: 'Uzbekistan', isoCode: 'UZB', isoCode2: 'UZ' },
  { name: 'Vanuatu', isoCode: 'VUT', isoCode2: 'VU' },
  { name: 'Vatican City', isoCode: 'VAT', isoCode2: 'VA' },
  { name: 'Venezuela', isoCode: 'VEN', isoCode2: 'VE' },
  { name: 'Vietnam', isoCode: 'VNM', isoCode2: 'VN' },
  { name: 'Yemen', isoCode: 'YEM', isoCode2: 'YE' },
  { name: 'Zambia', isoCode: 'ZMB', isoCode2: 'ZM' },
  { name: 'Zimbabwe', isoCode: 'ZWE', isoCode2: 'ZW' },
  /*
    Bonus places (2026-08-17): ISO territories with their own polygon in the
    50m atlas. Markable and painted, but is_territory keeps them out of every
    "X of the world" denominator. Existing databases get the same rows from
    migration 1787500000000-AddTerritories; keep both lists in step.
  */
  { name: 'Northern Mariana Islands', isoCode: 'MNP', isoCode2: 'MP', isTerritory: true },
  { name: 'U.S. Virgin Islands', isoCode: 'VIR', isoCode2: 'VI', isTerritory: true },
  { name: 'Guam', isoCode: 'GUM', isoCode2: 'GU', isTerritory: true },
  { name: 'American Samoa', isoCode: 'ASM', isoCode2: 'AS', isTerritory: true },
  { name: 'Puerto Rico', isoCode: 'PRI', isoCode2: 'PR', isTerritory: true },
  { name: 'Pitcairn Islands', isoCode: 'PCN', isoCode2: 'PN', isTerritory: true },
  { name: 'Falkland Islands', isoCode: 'FLK', isoCode2: 'FK', isTerritory: true },
  { name: 'Cayman Islands', isoCode: 'CYM', isoCode2: 'KY', isTerritory: true },
  { name: 'Bermuda', isoCode: 'BMU', isoCode2: 'BM', isTerritory: true },
  { name: 'Turks and Caicos Islands', isoCode: 'TCA', isoCode2: 'TC', isTerritory: true },
  { name: 'Niue', isoCode: 'NIU', isoCode2: 'NU', isTerritory: true },
  { name: 'Cook Islands', isoCode: 'COK', isoCode2: 'CK', isTerritory: true },
  { name: 'Western Sahara', isoCode: 'ESH', isoCode2: 'EH', isTerritory: true },
  { name: 'Saint Pierre and Miquelon', isoCode: 'SPM', isoCode2: 'PM', isTerritory: true },
  { name: 'Wallis and Futuna', isoCode: 'WLF', isoCode2: 'WF', isTerritory: true },
  { name: 'New Caledonia', isoCode: 'NCL', isoCode2: 'NC', isTerritory: true },
  { name: 'Greenland', isoCode: 'GRL', isoCode2: 'GL', isTerritory: true },
  { name: 'Faroe Islands', isoCode: 'FRO', isoCode2: 'FO', isTerritory: true },
  { name: 'Macao', isoCode: 'MAC', isoCode2: 'MO', isTerritory: true },
  { name: 'Hong Kong', isoCode: 'HKG', isoCode2: 'HK', isTerritory: true },
  { name: 'Norfolk Island', isoCode: 'NFK', isoCode2: 'NF', isTerritory: true },
  { name: 'South Georgia and the South Sandwich Islands', isoCode: 'SGS', isoCode2: 'GS', isTerritory: true },
  { name: 'British Indian Ocean Territory', isoCode: 'IOT', isoCode2: 'IO', isTerritory: true },
  { name: 'Saint Helena', isoCode: 'SHN', isoCode2: 'SH', isTerritory: true },
  { name: 'Anguilla', isoCode: 'AIA', isoCode2: 'AI', isTerritory: true },
  { name: 'British Virgin Islands', isoCode: 'VGB', isoCode2: 'VG', isTerritory: true },
  { name: 'Montserrat', isoCode: 'MSR', isoCode2: 'MS', isTerritory: true },
  { name: 'Jersey', isoCode: 'JEY', isoCode2: 'JE', isTerritory: true },
  { name: 'Guernsey', isoCode: 'GGY', isoCode2: 'GG', isTerritory: true },
  { name: 'Isle of Man', isoCode: 'IMN', isoCode2: 'IM', isTerritory: true },
  { name: 'Aruba', isoCode: 'ABW', isoCode2: 'AW', isTerritory: true },
  { name: 'Curaçao', isoCode: 'CUW', isoCode2: 'CW', isTerritory: true },
  { name: 'Saint Martin', isoCode: 'MAF', isoCode2: 'MF', isTerritory: true },
  { name: 'Saint Barthélemy', isoCode: 'BLM', isoCode2: 'BL', isTerritory: true },
  { name: 'French Polynesia', isoCode: 'PYF', isoCode2: 'PF', isTerritory: true },
  { name: 'French Southern Territories', isoCode: 'ATF', isoCode2: 'TF', isTerritory: true },
  { name: 'Åland Islands', isoCode: 'ALA', isoCode2: 'AX', isTerritory: true },
  { name: 'Heard Island and McDonald Islands', isoCode: 'HMD', isoCode2: 'HM', isTerritory: true },
  { name: 'Antarctica', isoCode: 'ATA', isoCode2: 'AQ', isTerritory: true },
  { name: 'Sint Maarten', isoCode: 'SXM', isoCode2: 'SX', isTerritory: true },
];

export async function seedCountries(dataSource: DataSource): Promise<void> {
  const countryRepository = dataSource.getRepository(Country);

  const existingCount = await countryRepository.count();
  if (existingCount > 0) {
    console.log('Countries already seeded. Skipping...');
    return;
  }

  console.log('Seeding countries...');
  await countryRepository.save(countriesData);
  console.log(`Seeded ${countriesData.length} countries.`);
}
